# -*- coding: utf-8 -*-
"""Week2_function_daily.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqGiqXcCpCzVMnmsqKMvuxa7ezjvE7jA

Apolo Barnabas
Week2Daily_Ch
"""

#Transforming the String into a 2D List
matrix_str = "1 2 3\n4 5 6\n7 8 9"
print(matrix_str)

matrix = [
    ['T', 's', 'i'],
    ['h', '%', 'x'],
    ['i', ' ', '#'],
    ['s', 'M', ' '],
    ['$', 'a', 't']
]

rows = len(matrix)
cols = len(matrix[0])

result = ""

for col in range(cols):        # iterate columns first
    for row in range(rows):    # then rows (top → bottom)
        result += matrix[row][col]

print(result)

matrix[row][col]

def read_alpha_matrix(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    result = ""

    for col in range(cols):
        for row in range(rows):
            char = matrix[row][col]
            if char.isalpha():
                result += char

    return result
    print(result)

result = "This$%is#Matrix!"

cleaned = ""
symbol_found = False

for i in range(len(result)):
    char = result[i]

    if char.isalpha():
        # If we saw symbols before AND this is not the first letter
        if symbol_found and len(cleaned) > 0:
            cleaned += " "

        cleaned += char
        symbol_found = False

    else:
        # mark that we saw symbols
        symbol_found = True

print(cleaned)

import re

def decode_matrix(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    raw = ""

    # Step 1: read column-wise
    for col in range(cols):
        for row in range(rows):
            raw += matrix[row][col]

    # Step 2: clean the string
    decoded = re.sub(r'(?<=[A-Za-z])[^A-Za-z]+(?=[A-Za-z])', ' ', raw)

    return decoded


# Example usage
matrix = [
    ['T', '%', 'i'],
    ['h', '!', 'x'],
    ['i', ' ', '#'],
    ['s', 'M', '$']
]

message = decode_matrix(matrix)
print(message)